export const countries = [
  {
    id: 'japan',
    name: '日本',
    flag: '\u{1F1EF}\u{1F1F5}',
    capital: '東京',
    lat: 36.2048,
    lng: 138.2529,
    difficulty: 'easy',
    description:
      '日本は、わたしたちが住んでいる島国です。海にかこまれていて、春・夏・秋・冬の四季があります。',
  },
  {
    id: 'usa',
    name: 'アメリカ',
    flag: '\u{1F1FA}\u{1F1F8}',
    capital: 'ワシントンD.C.',
    lat: 37.0902,
    lng: -95.7129,
    difficulty: 'easy',
    description:
      'アメリカは、とても広い国です。大きな都市や国立公園があり、いろいろな文化をもつ人たちがくらしています。',
  },
  {
    id: 'china',
    name: '中国',
    flag: '\u{1F1E8}\u{1F1F3}',
    capital: '北京',
    lat: 35.8617,
    lng: 104.1954,
    difficulty: 'easy',
    description:
      '中国は、世界で人口が多い国のひとつです。長い歴史があり、万里の長城など有名な場所があります。',
  },
  {
    id: 'korea',
    name: '韓国',
    flag: '\u{1F1F0}\u{1F1F7}',
    capital: 'ソウル',
    lat: 35.9078,
    lng: 127.7669,
    difficulty: 'easy',
    description:
      '韓国は、日本の近くにある国です。音楽や料理、歴史ある建物などで世界から注目されています。',
  },
  {
    id: 'india',
    name: 'インド',
    flag: '\u{1F1EE}\u{1F1F3}',
    capital: 'ニューデリー',
    lat: 20.5937,
    lng: 78.9629,
    difficulty: 'easy',
    description:
      'インドは、南アジアにある大きな国です。たくさんの言葉や文化があり、カレーなどの料理も有名です。',
  },
  {
    id: 'australia',
    name: 'オーストラリア',
    flag: '\u{1F1E6}\u{1F1FA}',
    capital: 'キャンベラ',
    lat: -25.2744,
    lng: 133.7751,
    difficulty: 'easy',
    description:
      'オーストラリアは、南半球にある広い国です。海や砂漠があり、めずらしい動物も多くすんでいます。',
  },
  {
    id: 'france',
    name: 'フランス',
    flag: '\u{1F1EB}\u{1F1F7}',
    capital: 'パリ',
    lat: 46.2276,
    lng: 2.2137,
    difficulty: 'easy',
    description:
      'フランスは、ヨーロッパにある国です。パリのエッフェル塔や美術館、パンやチーズでもよく知られています。',
  },
  {
    id: 'uk',
    name: 'イギリス',
    flag: '\u{1F1EC}\u{1F1E7}',
    capital: 'ロンドン',
    lat: 55.3781,
    lng: -3.436,
    difficulty: 'easy',
    description:
      'イギリスは、ヨーロッパの島国です。ロンドンには大きな時計台や古いお城があり、英語が使われています。',
  },
  {
    id: 'brazil',
    name: 'ブラジル',
    flag: '\u{1F1E7}\u{1F1F7}',
    capital: 'ブラジリア',
    lat: -14.235,
    lng: -51.9253,
    difficulty: 'easy',
    description:
      'ブラジルは、南アメリカでいちばん大きな国です。アマゾンの森やサッカー、にぎやかなお祭りが有名です。',
  },
  {
    id: 'egypt',
    name: 'エジプト',
    flag: '\u{1F1EA}\u{1F1EC}',
    capital: 'カイロ',
    lat: 26.8206,
    lng: 30.8025,
    difficulty: 'easy',
    description:
      'エジプトは、アフリカの北にある国です。ピラミッドやナイル川など、古代から続くすごい歴史があります。',
  },
  {
    id: 'canada',
    name: 'カナダ',
    flag: '\u{1F1E8}\u{1F1E6}',
    capital: 'オタワ',
    lat: 56.1304,
    lng: -106.3468,
    difficulty: 'normal',
    description:
      'カナダは、広い森や湖がたくさんある国です。冬はとても寒い地域もあり、自然が大切にされています。',
  },
  {
    id: 'mexico',
    name: 'メキシコ',
    flag: '\u{1F1F2}\u{1F1FD}',
    capital: 'メキシコシティ',
    lat: 23.6345,
    lng: -102.5528,
    difficulty: 'normal',
    description:
      'メキシコは、北アメリカの南にある国です。古い文明のあとや、色あざやかな祭り、タコスなどの料理で知られています。',
  },
  {
    id: 'germany',
    name: 'ドイツ',
    flag: '\u{1F1E9}\u{1F1EA}',
    capital: 'ベルリン',
    lat: 51.1657,
    lng: 10.4515,
    difficulty: 'normal',
    description:
      'ドイツは、ヨーロッパの中心に近い国です。車づくりや音楽、古いお城や町並みでも有名です。',
  },
  {
    id: 'italy',
    name: 'イタリア',
    flag: '\u{1F1EE}\u{1F1F9}',
    capital: 'ローマ',
    lat: 41.8719,
    lng: 12.5674,
    difficulty: 'normal',
    description:
      'イタリアは、ピザやパスタで有名な国です。ローマなどには、古い建物や美しい町がたくさんあります。',
  },
  {
    id: 'spain',
    name: 'スペイン',
    flag: '\u{1F1EA}\u{1F1F8}',
    capital: 'マドリード',
    lat: 40.4637,
    lng: -3.7492,
    difficulty: 'normal',
    description:
      'スペインは、ヨーロッパの南西にある国です。明るい広場やサッカー、フラメンコという踊りで知られています。',
  },
  {
    id: 'russia',
    name: 'ロシア',
    flag: '\u{1F1F7}\u{1F1FA}',
    capital: 'モスクワ',
    lat: 61.524,
    lng: 105.3188,
    difficulty: 'normal',
    description:
      'ロシアは、世界でとても広い国です。寒い地域が多く、モスクワには大きな広場や美しい教会があります。',
  },
  {
    id: 'thailand',
    name: 'タイ',
    flag: '\u{1F1F9}\u{1F1ED}',
    capital: 'バンコク',
    lat: 15.87,
    lng: 100.9925,
    difficulty: 'normal',
    description:
      'タイは、東南アジアにある国です。あたたかい気候で、お寺や屋台の料理、にぎやかな町が有名です。',
  },
  {
    id: 'indonesia',
    name: 'インドネシア',
    flag: '\u{1F1EE}\u{1F1E9}',
    capital: 'ジャカルタ',
    lat: -0.7893,
    lng: 113.9213,
    difficulty: 'normal',
    description:
      'インドネシアは、たくさんの島からできている国です。火山や海、森があり、いろいろな文化があります。',
  },
  {
    id: 'south-africa',
    name: '南アフリカ',
    flag: '\u{1F1FF}\u{1F1E6}',
    capital: 'プレトリア',
    lat: -30.5595,
    lng: 22.9375,
    difficulty: 'normal',
    description:
      '南アフリカは、アフリカの南にある国です。広い自然の中に、さまざまな動物や大きな都市があります。',
  },
  {
    id: 'saudi-arabia',
    name: 'サウジアラビア',
    flag: '\u{1F1F8}\u{1F1E6}',
    capital: 'リヤド',
    lat: 23.8859,
    lng: 45.0792,
    difficulty: 'normal',
    description:
      'サウジアラビアは、中東にある国です。広い砂漠があり、石油やイスラム教の大切な場所でも知られています。',
  },
  {
    id: 'argentina',
    name: 'アルゼンチン',
    flag: '\u{1F1E6}\u{1F1F7}',
    capital: 'ブエノスアイレス',
    lat: -38.4161,
    lng: -63.6167,
    difficulty: 'hard',
    description:
      'アルゼンチンは、南アメリカの南に広がる国です。サッカーやタンゴ、草原や山の景色で有名です。',
  },
  {
    id: 'chile',
    name: 'チリ',
    flag: '\u{1F1E8}\u{1F1F1}',
    capital: 'サンティアゴ',
    lat: -35.6751,
    lng: -71.543,
    difficulty: 'hard',
    description:
      'チリは、南アメリカの西側に細長くのびる国です。海、砂漠、高い山など、いろいろな自然があります。',
  },
  {
    id: 'peru',
    name: 'ペルー',
    flag: '\u{1F1F5}\u{1F1EA}',
    capital: 'リマ',
    lat: -9.19,
    lng: -75.0152,
    difficulty: 'hard',
    description:
      'ペルーは、南アメリカにある国です。アンデス山脈や、古いインカの町マチュピチュで知られています。',
  },
  {
    id: 'turkey',
    name: 'トルコ',
    flag: '\u{1F1F9}\u{1F1F7}',
    capital: 'アンカラ',
    lat: 38.9637,
    lng: 35.2433,
    difficulty: 'hard',
    description:
      'トルコは、ヨーロッパとアジアの間にある国です。古くから多くの人や文化が行き来してきました。',
  },
  {
    id: 'greece',
    name: 'ギリシャ',
    flag: '\u{1F1EC}\u{1F1F7}',
    capital: 'アテネ',
    lat: 39.0742,
    lng: 21.8243,
    difficulty: 'hard',
    description:
      'ギリシャは、ヨーロッパの南にある国です。古代の神話や神殿、青い海にうかぶ島々で有名です。',
  },
  {
    id: 'netherlands',
    name: 'オランダ',
    flag: '\u{1F1F3}\u{1F1F1}',
    capital: 'アムステルダム',
    lat: 52.1326,
    lng: 5.2913,
    difficulty: 'hard',
    description:
      'オランダは、ヨーロッパの低い土地にある国です。運河や風車、チューリップの花でよく知られています。',
  },
  {
    id: 'sweden',
    name: 'スウェーデン',
    flag: '\u{1F1F8}\u{1F1EA}',
    capital: 'ストックホルム',
    lat: 60.1282,
    lng: 18.6435,
    difficulty: 'hard',
    description:
      'スウェーデンは、北ヨーロッパにある国です。森や湖が多く、冬には雪がふる地域もたくさんあります。',
  },
  {
    id: 'new-zealand',
    name: 'ニュージーランド',
    flag: '\u{1F1F3}\u{1F1FF}',
    capital: 'ウェリントン',
    lat: -40.9006,
    lng: 174.886,
    difficulty: 'hard',
    description:
      'ニュージーランドは、南半球にある島国です。山や牧場、きれいな湖など、自然の景色がとても豊かです。',
  },
  {
    id: 'vietnam',
    name: 'ベトナム',
    flag: '\u{1F1FB}\u{1F1F3}',
    capital: 'ハノイ',
    lat: 14.0583,
    lng: 108.2772,
    difficulty: 'hard',
    description:
      'ベトナムは、東南アジアにある細長い国です。米づくりがさかんで、川や市場、にぎやかな町があります。',
  },
  {
    id: 'singapore',
    name: 'シンガポール',
    flag: '\u{1F1F8}\u{1F1EC}',
    capital: 'シンガポール',
    lat: 1.3521,
    lng: 103.8198,
    difficulty: 'hard',
    description:
      'シンガポールは、東南アジアにある小さな国です。港や高いビルが多く、いろいろな文化が集まっています。',
  },
];
